-- 0002_better_auth.sql — Better Auth schema (single source of the auth schema).
--
-- Generated by `bunx @better-auth/cli generate` against apps/web/lib/auth.ts
-- (email+password, social google/apple, plugins: jwt/bearer/expo), then adapted
-- to plain, idempotent Postgres DDL. The Go migrate runner globs migrations/*.sql
-- in lexicographic order and execs each file whole, so the Go boot-migrations own
-- the ENTIRE schema — there is NO JS migration step at deploy.
--
-- Better Auth is the identity provider hosted by the Next.js web app at
-- ${BETTER_AUTH_URL}/api/auth/*. These tables live in the SAME Postgres as the
-- Go API; the Go backend is a pure resource server that verifies EdDSA JWTs via
-- /api/auth/jwks and upserts the domain `users` mirror (0001_init.sql) from the
-- JWT `sub`/email/name claims. Camel-cased, quoted identifiers match the names
-- Better Auth's Kysely adapter expects verbatim — do not snake_case them.

CREATE TABLE IF NOT EXISTS "user" (
    "id"            text NOT NULL PRIMARY KEY,
    "name"          text NOT NULL,
    "email"         text NOT NULL UNIQUE,
    "emailVerified" boolean NOT NULL,
    "image"         text,
    "createdAt"     timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"     timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "session" (
    "id"        text NOT NULL PRIMARY KEY,
    "expiresAt" timestamptz NOT NULL,
    "token"     text NOT NULL UNIQUE,
    "createdAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamptz NOT NULL,
    "ipAddress" text,
    "userAgent" text,
    "userId"    text NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "account" (
    "id"                    text NOT NULL PRIMARY KEY,
    "accountId"             text NOT NULL,
    "providerId"            text NOT NULL,
    "userId"                text NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE,
    "accessToken"           text,
    "refreshToken"          text,
    "idToken"               text,
    "accessTokenExpiresAt"  timestamptz,
    "refreshTokenExpiresAt" timestamptz,
    "scope"                 text,
    "password"              text,
    "createdAt"             timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"             timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS "verification" (
    "id"         text NOT NULL PRIMARY KEY,
    "identifier" text NOT NULL,
    "value"      text NOT NULL,
    "expiresAt"  timestamptz NOT NULL,
    "createdAt"  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "jwks" (
    "id"         text NOT NULL PRIMARY KEY,
    "publicKey"  text NOT NULL,
    "privateKey" text NOT NULL,
    "createdAt"  timestamptz NOT NULL,
    "expiresAt"  timestamptz
);

CREATE INDEX IF NOT EXISTS "session_userId_idx" ON "session" ("userId");
CREATE INDEX IF NOT EXISTS "account_userId_idx" ON "account" ("userId");
CREATE INDEX IF NOT EXISTS "verification_identifier_idx" ON "verification" ("identifier");
